import type { Role } from '@beercanlabs/factory-auth';

/**
 * The privileges the control plane's routes ask for, one name per kind of action (the census in DESIGN_AUTHORITY.md,
 * work stream "Bouncer flow"). A route asks the Bouncer for one named privilege; it never names a role.
 */
export const PRIVILEGES = [
  'agents.read',
  'policy.read',
  'config.read',
  'runs.read',
  'ledger.read',
  'models.read',
  'metrics.read',
  'triage.read',
  'spend.read',
  'approvals.read',
  'skills.read',
  'skills.register',
  'systems.read',
  'systems.propose',
  'connections.read',
  'credentials.provider.read',
  'events.subscribe',
  'schedules.read',
  'mcp.use',
  'agents.wake',
  'agents.pause',
  'agents.resume',
  'agents.isolate',
  'runs.cancel',
  'agents.converse',
  'hooks.invoke',
  'schedules.write',
  'runs.attest-requester',
  'approvals.decide',
  'ledger.ingest',
  'ledger.attest-run-actor',
  'egress.run.read',
  'egress.approvals.request',
  'egress.holds.create',
  'egress.approvals.consume',
  'egress.keymaster.checkout',
  'egress.progress.report',
  'egress.routes.read',
  'egress.connections.token',
  'registry.register',
  'registry.budget.set',
  'registry.retire',
  'registry.reinstate',
  'registry.purge',
  'registry.deploy',
  'registry.model.set',
  'policy.set',
  'policy.budget.set',
  'config.export',
  'config.export.agent',
  'agents.owners.set',
  'identity.links.read',
  'identity.links.set',
  'credentials.outstanding.read',
  'credentials.platform.read',
  'credentials.platform.set',
  'credentials.agent.read',
  'credentials.agent.set',
  'credentials.provider.set',
  'connections.start',
  'connections.import',
  'systems.decide',
  'skills.decide',
  'skills.checks.run',
] as const;

export type Privilege = (typeof PRIVILEGES)[number];

/**
 * Role to privileges, in full. Users map to roles and roles map to privileges, never a user to a privilege.
 * Built into the code (Dale, 2026-10-03); making it factory data an admin edits is a later enhancement, so read
 * this table only through `authorize`: never import it elsewhere.
 */
export const ROLE_PRIVILEGES: Record<Role, readonly Privilege[]> = {
  // Reads. An operator and an approver also hold every viewer privilege.
  viewer: [
    'agents.read',
    'policy.read',
    'config.read',
    'runs.read',
    'ledger.read',
    'models.read',
    'metrics.read',
    'triage.read',
    'spend.read',
    'approvals.read',
    'skills.read',
    'skills.register',
    'systems.read',
    'systems.propose',
    'connections.read',
    'credentials.provider.read',
    'events.subscribe',
    'schedules.read',
    'mcp.use',
  ],
  operator: [
    'agents.read',
    'policy.read',
    'config.read',
    'runs.read',
    'ledger.read',
    'models.read',
    'metrics.read',
    'triage.read',
    'spend.read',
    'approvals.read',
    'skills.read',
    'skills.register',
    'systems.read',
    'systems.propose',
    'connections.read',
    'credentials.provider.read',
    'events.subscribe',
    'schedules.read',
    'mcp.use',
    'agents.wake',
    'agents.pause',
    'agents.resume',
    'agents.isolate',
    'runs.cancel',
    'agents.converse',
    'hooks.invoke',
    'schedules.write',
  ],
  approver: [
    'agents.read',
    'policy.read',
    'config.read',
    'runs.read',
    'ledger.read',
    'models.read',
    'metrics.read',
    'triage.read',
    'spend.read',
    'approvals.read',
    'skills.read',
    'skills.register',
    'systems.read',
    'systems.propose',
    'connections.read',
    'credentials.provider.read',
    'events.subscribe',
    'schedules.read',
    'mcp.use',
    'approvals.decide',
  ],
  ingest: [
    'ledger.ingest',
  ],
  // The egress holds the ingest privileges too. Two of these are exclusive: an admin does not hold them.
  'gatekeeper-egress': [
    'ledger.ingest',
    'ledger.attest-run-actor',
    'egress.run.read',
    'egress.approvals.request',
    'egress.holds.create',
    'egress.approvals.consume',
    'egress.keymaster.checkout',
    'egress.progress.report',
    'egress.routes.read',
    'egress.connections.token',
  ],
  // The ingress is the one party that sees who sent a message, so it alone may say who asked (Dale, 2026-10-04: an
  // operator or admin must not be able to name the requester). Its token also carries `operator`, which it needs to
  // wake agents and hand off messages.
  'gatekeeper-ingress': [
    'runs.attest-requester',
  ],
  // Everything except the exclusive privileges.
  admin: [
    'agents.read',
    'policy.read',
    'config.read',
    'runs.read',
    'ledger.read',
    'models.read',
    'metrics.read',
    'triage.read',
    'spend.read',
    'approvals.read',
    'skills.read',
    'skills.register',
    'systems.read',
    'systems.propose',
    'connections.read',
    'credentials.provider.read',
    'events.subscribe',
    'schedules.read',
    'mcp.use',
    'agents.wake',
    'agents.pause',
    'agents.resume',
    'agents.isolate',
    'runs.cancel',
    'agents.converse',
    'hooks.invoke',
    'schedules.write',
    'approvals.decide',
    'ledger.ingest',
    'egress.run.read',
    'egress.approvals.request',
    'egress.holds.create',
    'egress.approvals.consume',
    'egress.keymaster.checkout',
    'egress.progress.report',
    'egress.routes.read',
    'registry.register',
    'registry.budget.set',
    'registry.retire',
    'registry.reinstate',
    'registry.purge',
    'registry.deploy',
    'registry.model.set',
    'policy.set',
    'policy.budget.set',
    'config.export',
    'config.export.agent',
    'agents.owners.set',
    'identity.links.read',
    'identity.links.set',
    'credentials.outstanding.read',
    'credentials.platform.read',
    'credentials.platform.set',
    'credentials.agent.read',
    'credentials.agent.set',
    'credentials.provider.set',
    'connections.start',
    'connections.import',
    'systems.decide',
    'skills.decide',
    'skills.checks.run',
  ],
};

/**
 * Privileges that act on one agent, so a route can pass that agent as the resource. Only these can be held through
 * ownership or as the requester; every other privilege is fleet-wide and is held by roles alone.
 */
export const AGENT_SCOPED: ReadonlySet<Privilege> = new Set<Privilege>([
  'agents.wake',
  'agents.pause',
  'agents.resume',
  'config.read',
  'config.export.agent',
  'credentials.agent.read',
  'credentials.agent.set',
  'connections.start',
  'connections.import',
  'approvals.decide',
]);

/** The roles that are derived from data about one agent or run, never read from a credential or a claim. */
export type DerivedRole = 'agent-owner' | 'requester';

/**
 * What a derived role holds, on its own agent only (Dale, 2026-10-03). `approvals.decide` is held by an owner only
 * when the run has no requesting user (see `authorize`); the requester holds it for its own run.
 */
export const DERIVED_ROLE_PRIVILEGES: Record<DerivedRole, readonly Privilege[]> = {
  'agent-owner': [
    'config.read',
    'config.export.agent',
    'credentials.agent.read',
    'credentials.agent.set',
    'connections.start',
    'connections.import',
    'agents.wake',
    'agents.pause',
    'agents.resume',
    'approvals.decide',
  ],
  requester: ['approvals.decide'],
};
